language: julia
os:
  - linux
  - osx
julia:
  - 0.4
#  - nightly
before_install:
  - sudo apt-get install python-numpy python-scipy libpcre3-dev gfortran -y # this may not be neccesary
  - dpkg --get-selections | grep -v deinstall # list installed packages
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Mass2"); Pkg.test("Mass2"; coverage=true)'
