sudo: false # run on travis's container based infrastructure
language: julia
os:
  - linux
julia:
  - 0.4
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib
    - libpcre3-dev
    - gfortran
# before_install:
#   - sudo apt-get install python-numpy python-scipy python-matplotlib libpcre3-dev gfortran -y # this may not be neccesary
#   - dpkg --get-selections | grep -v deinstall # list installed packages
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Mass2"); Pkg.test("Mass2"; coverage=true)'
